version: "2.4"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bedrock-sage-db:/var/lib/mysql
    ports:
      - 3306:3306

  bedrock:
    build:
      dockerfile: docker/bedrock.Dockerfile
      context: ${PWD:-.}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD:-.}/bedrock:/app/bedrock
      - /var/cache/composer
    ports:
      - 8080:8080
    depends_on:
      - db

  sage:
    build:
      dockerfile: docker/sage.Dockerfile
      context: ${PWD:-.}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD:-.}/sage:/app/sage
      - /var/cache/yarn
    depends_on:
      - bedrock
    ports:
      - 80:3000
      - 81:3001


volumes:
  bedrock-sage-db:
